table only

diff --git a/.github/workflows/pytest-coverage.yml b/.github/workflows/pytest-coverage.yml
--- a/.github/workflows/pytest-coverage.yml
+++ b/.github/workflows/pytest-coverage.yml
@@ -67,11 +67,11 @@ jobs:
     #     labels: worflow-failed
     #     body: ${{ steps.pytester-cov.outputs.output-table }}
 
-    - name: Coverage single fail - exit
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-        exit 1
+    # - name: Coverage single fail - exit
+    #   if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+    #   run: |
+    #     echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+    #     exit 1
 
     # - name: Coverage total fail - new issue
     #   if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
@@ -83,11 +83,11 @@ jobs:
     #     labels: worflow-failed
     #     body: ${{ steps.pytester-cov.outputs.output-table }}
 
-    - name: Coverage total fail - exit
-      # if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-        exit 1
+    # - name: Coverage total fail - exit
+    #   # if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+    #   run: |
+    #     echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+    #     exit 1
 
     - name: Commit pytest coverage table
       uses: peter-evans/commit-comment@v1
