draft workflow

diff --git a/.github/workflows/pytest-coverage.yml b/.github/workflows/pytest-coverage.yml
--- a/.github/workflows/pytest-coverage.yml
+++ b/.github/workflows/pytest-coverage.yml
@@ -1,38 +1,95 @@
-name: actions pytest coverage
+# **************************************************************************************************************** #
+# This workflow will install Python dependencies, and run pytest --cov on all files recursively from the pytest-root-dir
+# The workflow is also configured to exit with error if minimum individual file or total pytest coverage minimum not met
+# If the workflow exits with error, an informative issue is created for the repo alerting the user
+# If the workflow succeeds, a commit message is generated with the pytest --cov markdown table
+#
+# Variables to set:
+#   * pytester action:
+#     * pytest-root-dir: top-level directory to recursively check all .py files for pytest --cov
+#     * cov-omit-list: comma separated str of all files and/or dirs to ignore
+#   * env:
+#     * cov-threshold-single: minimum individual file coverage required
+#     * cov-threshold-total: minimum total coverage required
+#
+# Action outputs:
+#   * output-table: `pytest --cov` markdown output table
+#   * cov-threshold-single-fail: `false` if any single file coverage less than `cov-threshold-single`, else `true`
+#   * cov-threshold-total-fail: `false` if total coverage less than `cov-threshold-total`, else `true`
+#
+# Workflows used:
+#   * actions/checkout@v2: checkout files to perform additional actions on
+#   * alexanderdamiani/pytester-cov@v1.0.0: runs pytest --cov and associated functions
+#   * nashmaniac/create-issue-action@v1.1: creates issue for repo
+#   * peter-evans/commit-comment@v1: adds message to commit
+# **************************************************************************************************************** #
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+name: Pytest coverage
+
+on: [push, pull_request, workflow_dispatch]
 
 jobs:
   build:
 
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: [3.9]
+    env:
+      COVERAGE_SINGLE: 60
+      COVERAGE_TOTAL: 60
 
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
+    - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
-        python-version: ${{ matrix.python-version }}
+        python-version: 3.9
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        python -m pip install flake8 pytest coverage
-        pip install -r .github/.manifest/requirements.txt
-        pip install -e .
-    - name: Lint with flake8
+        pip install flake8 pytest
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+    - name: pytester-cov
+      id: pytester-cov
+      uses: alexanderdamiani/pytester-cov@v1.2.1
+      with:
+        pytest-root-dir: '.'
+        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+
+    # - name: Coverage single fail - new issue
+    #   if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+    #   uses: nashmaniac/create-issue-action@v1.1
+    #   with:
+    #     title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+    #     token: ${{secrets.GITHUB_TOKEN}}
+    #     assignees: ${{github.actor}}
+    #     labels: worflow-failed
+    #     body: ${{ steps.pytester-cov.outputs.output-table }}
+
+    - name: Coverage single fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest, benchmark and submit coverage to codecov.io
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+        exit 1
+
+    # - name: Coverage total fail - new issue
+    #   if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+    #   uses: nashmaniac/create-issue-action@v1.1
+    #   with:
+    #     title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+    #     token: ${{secrets.GITHUB_TOKEN}}
+    #     assignees: ${{github.actor}}
+    #     labels: worflow-failed
+    #     body: ${{ steps.pytester-cov.outputs.output-table }}
+
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
       run: |
-        coverage run -m pytest --benchmark-skip
-        bash <(curl -s https://codecov.io/bash)
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
+
+    - name: Commit pytest coverage table
+      uses: peter-evans/commit-comment@v1
+      with:
+        body: ${{ steps.pytester-cov.outputs.output-table }}
